### ISSUE TITLE
Sometimes the end screen of the game is the mirror image

### ISSUE THREAD

**Issue by miok** [jcollard/elmtris#4]
Sometimes while playing the last screen of the game is the mirror image

![screenshot](https://cloud.githubusercontent.com/assets/2442401/10871759/902b6eca-80f8-11e5-953a-f45da3c7e37a.png)

**Comment by jcollard** [comment]
This was a bug in Elm version 10 so it shouldn't be a problem if someone were to convert the game to the latest version.

Thanks for letting me know :)
