### ISSUE TITLE
What.

### ISSUE THREAD

**Issue by ryan-haskell** [jcollard/elmtris#7]
I wanted to learn Elm Programming, but your elmtris game was so fun I played it instead. Good work, dude.

Anyway, after my second game something weird went down. When the game was over, I saw this:

![image](https://cloud.githubusercontent.com/assets/6187256/19405008/dfcaa306-9227-11e6-80b7-08554608c2ab.png)

I can't even begin to understand what would make this happen.

Good game, and good luck.

**Comment by jcollard** [comment]
This is actually an issue with Elm 0.10.0 that has been fixed (not actually a bug in my code). Unfortunately, this code is for a very old version of elm and isn't a good spot to learn.

I do have an unfinished YouTube series where I walk through writing Tetris in Elm. I abandoned it when I learned Elm 0.17.0 would no longer have the Graphics library I was using. The Graphics library can be installed if you have Elm on your own system. You may still find it useful: https://www.youtube.com/captaincoder

Best of luck!
